name: Kranitel
version: ${version}
main: it.ilgrandeanonimo.kranitel.Kranitel
description: Kranitel allows you to change commands permissions.
author: IlGrandeAnonimo
api-version: '1.21.1'
load: POSTWORLD